DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  `hashed_password` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `index_username` (`username`)
) ENGINE=InnoDB;

-- Some dummy users for testing purposes. Password for both users is password
INSERT INTO users VALUES
(1, "sherlock@holmes.com", "sherlock007", "$2y$10$YZLnCUBxMxhiXL8OuPQh0.DBSBxIxgizBzIPGqsRPmNBLid.5RYbC"),
(2, "john@smith.com", "johnsmith", "$2y$10$YhTgRREy837o.4xym2s66ufnW.0ORG43TYTnyKFqcbfjXsVqqPKUa");

DROP TABLE IF EXISTS `blogs`;
CREATE TABLE `blogs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `create_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `update_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB;

-- Some dummy content for the blogsite. Content is from Wikipedia
INSERT INTO blogs (user_id, title, content, create_date, update_date) VALUES
(1, "Started watching Broadchurch because of David Tenant. Stayed for the plot",
  "Broadchurch is a British serial crime drama television series broadcast on ITV for three seasons between 2013 and 2017. It was created by Chris Chibnall, who acted as an executive producer and wrote all 24 episodes, and produced by Kudos Film and Television, Shine America, and Imaginary Friends. The series is set in Broadchurch, a fictional English town in Dorset, and focuses on police detectives DI Alec Hardy (David Tennant) and DS Ellie Miller (Olivia Colman). The series features an ensemble cast that in addition to Tennant and Colman includes Jodie Whittaker, Andrew Buchan, Carolyn Pickles, Arthur Darvill, Charlotte Beaumont, Adam Wilson and Matthew Gravelle.\r\rThe first series, which premiered on 4 March 2013, focuses on the death of local 11-year-old Danny Latimer and the impact of grief, mutual suspicion and media attention on the town. Danny's family (his mother, Beth, father, Mark and sister, Chloe) are a key focus for the first series. The second series, which premiered on 5 January 2015, follows the dual storylines of bringing Danny's killer to justice and a case from the past returning to haunt Hardy. The third and final series, which premiered on 27 February 2017, focuses on the rape of a local woman at a birthday party, while the Latimer family go to extreme lengths to move on from Danny's death. Chibnall has indicated that the third series will be the last and that he originally envisioned Broadchurch as being a trilogy.\r\rAll three series received critical acclaim, with praise directed towards the writing, cinematography and character development.",
  "2018-01-27", "2018-01-27"),
(1, "Doctor Who. Time travel is weird. The world would probably end if people could go back in time and change things.",
  "Just Doctor Who is a British science fiction television programme produced by the BBC since 1963. The programme depicts the adventures of a Time Lord called 'the Doctor', an extraterrestrial being, to all appearances human, from the planet Gallifrey. The Doctor explores the universe in a time-travelling space ship called the TARDIS. Its exterior appears as a blue British police box, which was a common sight in Britain in 1963 when the series first aired. Accompanied by a number of companions, the Doctor combats a variety of foes while working to save civilisations and help people in need.\r\rThe show is a significant part of British popular culture, and elsewhere it has gained a cult following. It has influenced generations of British television professionals, many of whom grew up watching the series. The programme originally ran from 1963 to 1989. There was an unsuccessful attempt to revive regular production in 1996 with a backdoor pilot, in the form of a television film titled Doctor Who. The programme was relaunched in 2005, and since then has been produced in-house by BBC Wales in Cardiff. Doctor Who has also spawned numerous spin-offs, including comic books, films, novels, audio dramas, and the television series Torchwood (2006–2011), The Sarah Jane Adventures (2007–2011), K-9 (2009–2010), and Class (2016), and has been the subject of many parodies and references in popular culture.\r\rThirteen actors have headlined the series as the Doctor. The transition from one actor to another is written into the plot of the show with the concept of regeneration into a new incarnation, a plot device in which a Time Lord 'transforms' into a new body when the current one is too badly harmed to heal normally. Each actor's portrayal is unique, but all represent stages in the life of the same character. Together, they form a single lifetime with a single narrative. The time-travelling feature of the plot means that different incarnations of the Doctor occasionally meet. The Doctor is currently portrayed by Jodie Whittaker, who took on the role after Peter Capaldi's exit in the 2017 Christmas special 'Twice Upon a Time'.",
"2018-02-15", "2018-02-15"),
(2, "Can we just talk about The Umbrella Academy? Such a good show",
  "The Umbrella Academy is an American superhero web television series developed by Steve Blackman and Jeremy Slater for Netflix. It is an adaptation of the comic book series of the same name, created by Gerard Way and Gabriel Ba, and published by Dark Horse Comics. The plot revolves around a dysfunctional family of adopted sibling superheroes who reunite to solve the mystery of their father's death, and the threat of an impending apocalypse.\r\rThe ensemble cast features Ellen Page, Tom Hopper, David Castaneda, Emmy Raver-Lampman, Robert Sheehan, Aidan Gallagher, Cameron Britton, and Mary J. Blige. The adaptation began development as a film optioned by Universal Pictures in 2011. However, it was eventually shelved in favor of a television series in 2015, before being officially greenlit by Netflix in July 2017. The series is filmed in Toronto and Hamilton, Ontario, Canada.",
  "2018-03-24", "2018-03-24"),
(2, "Lord of the Rings is probably one of the best film trilogies, ever",
  "The Lord of the Rings is a film series of three epic fantasy adventure films directed by Peter Jackson, based on the novel written by J. R. R. Tolkien. The films are subtitled The Fellowship of the Ring (2001), The Two Towers (2002) and The Return of the King (2003). Produced and distributed by New Line Cinema with the co-production of WingNut Films, it is an international venture between New Zealand and the United States. The films feature an ensemble cast including Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mortensen, Sean Astin, Cate Blanchett, John Rhys-Davies, Christopher Lee, Billy Boyd, Dominic Monaghan, Orlando Bloom, Hugo Weaving, Andy Serkis and Sean Bean.\r\rSet in the fictional world of Middle-earth, the films follow the hobbit Frodo Baggins as he and the Fellowship embark on a quest to destroy the One Ring, to ensure the destruction of its maker, the Dark Lord Sauron. The Fellowship eventually splits up and Frodo continues the quest with his loyal companion Sam and the treacherous Gollum. Meanwhile, Aragorn, heir in exile to the throne of Gondor, along with Legolas, Gimli, Merry, Pippin and the wizard Gandalf, unite to rally the Free Peoples of Middle-earth in the War of the Ring in order to aid Frodo by weakening Sauron's forces.\r\rThe three films were shot simultaneously and entirely in Jackson's native New Zealand from 11 October 1999 until 22 December 2000, with pick-up shots done from 2001 to 2004. It was one of the biggest and most ambitious film projects ever undertaken, with a budget of $281 million. An extended edition of each film was released on home video a year after its theatrical release.",
  "2018-04-18", "2018-04-18"),
(2, "When it comes to superheroes movies, it's hard to beat The Dark Knight Trilogy",
  "The Dark Knight Series is a set of three Christopher Nolan Batman movies. It includes Batman Begins (2005), The Dark Knight (2008), and The Dark Knight Rises (2012). Christian Bale, Michael Caine, Gary Oldman, Morgan Freeman, and Cillian Murphy appeared in all three movies. All cast and crew members worked on all three movies, except for music composer James Newton Howard who did not work on The Dark Knight Rises. Composer Hans Zimmer worked together with Howard on the first two films and made the soundtrack for the last movie by himself. Katie Holmes played Rachel Dawes in Batman Begins, but was replaced by Maggie Gyllenhaal in The Dark Knight. Liam Neeson appeared as Ra's al Ghul in Batman Begins and in The Dark Knight Rises.\r\rHeath Ledger received an Academy Award for Best Supporting Actor for his role as The Joker in The Dark Knight. Ledger died before the movie was released and the award was given posthumously.\r\rEach of the three movies was a success in the box office; The Dark Knight was the number one grossing movie in 2008. The Dark Knight Rises is the third highest grossing movie of 2012. Batman Begins is the ninth highest grossing movie in 2005. Batman Begins earned $372,710,015 worldwide. The Dark Knight earned $1,023,045,358. The Dark Knight Rises earned $1,081,041,287, passing the receipts of The Dark Knight. In both Batman Begins and in The Dark Knight, Gotham City was shot in Chicago, Illinois.\r\rIn The Dark Knight Rises, Gotham City was shot in Pittsburgh, Pennsylvania, New York City, New York, and Los Angeles, California.",
  "2018-05-24", "2018-05-24"),
(1, "The Bootstrap Paradox is such a weird time travel concept",
  "The Bootstrap Paradox, also known as 'casual loop',  is a theoretical proposition in which, by means of either retrocausality or time travel, a sequence of events (actions, information, objects, people) is among the causes of another event, which is in turn among the causes of the first-mentioned event. Such causally looped events then exist in spacetime, but their origin cannot be determined. A hypothetical example of a causality loop is given of a billiard ball striking its past self: the billiard ball moves in a path towards a time machine, and the future self of the billiard ball emerges from the time machine before its past self enters it, giving its past self a glancing blow, altering the past ball's path and causing it to enter the time machine at an angle that would cause its future self to strike its past self the very glancing blow that altered its path.\r\rYeah, I don't get it either. But there's a prety good Doctor Who episode about it.",
  "2018-06-15", "2018-06-15"),
(2, "It was only 13 episodes long but Sherlock was a great tv show. Benedict Cumberbatch's portrayal of Sherlock Holmes is still one of the best, IMO",
  "Sherlock is a British crime drama television series based on Sir Arthur Conan Doyle's Sherlock Holmes detective stories. Created by Steven Moffat and Mark Gatiss, it stars Benedict Cumberbatch as Sherlock Holmes and Martin Freeman as Doctor John Watson. 13 episodes have been produced, with four three-part series airing from 2010 to 2017, and a special episode that aired on 1 January 2016. The series is set in the present day, while the one-off special features a Victorian period fantasy resembling the original Holmes stories. Sherlock is produced by the British network BBC, along with Hartswood Films, with Moffat, Gatiss, Sue Vertue and Rebecca Eaton serving as executive producers. The series is supported by the American station WGBH-TV Boston for its Masterpiece anthology series on PBS, where it also airs in the United States. The series is primarily filmed in Cardiff, Wales, with North Gower Street in London used for exterior shots of Holmes and Watson's 221B Baker Street residence.\r\rSherlock has been praised for the quality of its writing, acting, and direction. It has been nominated for numerous awards including Emmys, BAFTAs and a Golden Globe, winning several awards across a variety of categories. The show won in three categories at the 66th Primetime Emmy Awards including Outstanding Lead Actor in a Miniseries or a Movie for Cumberbatch, Outstanding Supporting Actor in a Miniseries or a Movie for Freeman and Outstanding Writing for a Miniseries, Movie or a Dramatic Special for Moffat. Two years later, it won Outstanding Television Movie. In addition, the show was also honoured with a Peabody Award in 2011.",
  "2018-07-18", "2018-07-18"),
(1, "Not really into the horror genre or the 80's, but still enjoyed Stranger Things.",
  "Stranger Things is an American science fiction horror web television series created by the Duffer Brothers and released on Netflix. The siblings also serve as executive producers with Shawn Levy and Dan Cohen. The first season stars Winona Ryder, David Harbour, Finn Wolfhard, Millie Bobby Brown, Gaten Matarazzo, Caleb McLaughlin, Natalia Dyer, Charlie Heaton, Cara Buono, and Matthew Modine, with Noah Schnapp and Joe Keery in recurring roles. For the second season, Schnapp and Keery were made series regulars, as were newly cast Sadie Sink, Dacre Montgomery, Sean Astin, and Paul Reiser, with Priah Ferguson appearing in a recurring role. Maya Hawke joined the cast for the third season, while Ferguson was promoted to a series regular.\r\rSet in the fictional town of Hawkins, Indiana, in November 1983, the first season focuses on the investigation into the disappearance of a young boy amid supernatural events occurring around the town, including the appearance of a girl with psychokinetic abilities who helps the missing boy's friends in their search. The second season, titled Stranger Things 2, is set one year later in October 1984 and deals with the characters' attempts to return to normality and the aftermath of the events from the first season. The third season, titled Stranger Things 3, is set in July 1985.\r\rThe Duffer Brothers developed the series as a mix of investigative drama alongside supernatural elements portrayed with childlike sensibilities. They set the series in the 1980s and created an homage to the pop culture of that decade. Several themes and directorial aspects were inspired and aesthetically informed by the works of Steven Spielberg, John Carpenter, and Stephen King, among others, including several films, anime, and video games.\r\rThe first season of eight episodes premiered on Netflix on July 15, 2016. It received critical acclaim for its characterization, pacing, atmosphere, acting, soundtrack, directing, writing, and homages to 1980s films. The second season consisting of nine episodes was released on October 27, 2017. A third season consisting of eight episodes was released on July 4, 2019. The Duffer Brothers have said that Stranger Things is likely to end after its fourth or fifth season. The series has received 31 Primetime Emmy Award nominations, including for Outstanding Drama Series, and four Golden Globe Award nominations, and it won the Screen Actors Guild Award for Outstanding Performance by an Ensemble in a Drama Series in 2016.",
  "2018-08-19", "2018-08-19"),
(2, "When it comes to animated shows, Avatar: The Last Airbender is my favourite. Can't wait for the live-action remake of the series",
  "Avatar: The Last Airbender (Avatar: The Legend of Aang in some regions) is an American animated television series created by Bryan Konietzko and Michael Dante DiMartino that aired for three seasons on Nickelodeon. The series began airing in February 2005 and concluded in July 2008. Avatar: The Last Airbender is set in an Asiatic-like world in which some people can manipulate the classical elements with psychokinetic variants of the Chinese martial arts known as 'bending'. The series is presented in a style that combines anime with American cartoons and relies on the imagery of East/South Asian, Inuit, and New World societies. It follows the protagonists, 12-year-old Aang and his friends, who must bring peace and unity to the world by ending the Fire Lord's war with the rest of the world.\r\rThe series was commercially successful and was acclaimed by audiences and critics, who praised its art direction, humor, cultural references, characters, and themes. It was nominated for—and won—Annie Awards, Genesis Awards, a Primetime Emmy Award, and a Peabody Award. The first season's success prompted Nickelodeon to order a second and third season. Merchandising for the series consisted of action figures, a trading card game, three video games, stuffed animals distributed by Paramount Parks, and two Lego sets. An art book was published in June 2010. The complete series was released on Blu-ray on June 5, 2018 for the 10th anniversary of season 3's finale.\r\rThe series inspired a critically panned but financially successful live-action film, The Last Airbender, directed by M. Night Shyamalan and considered one of the worst movies ever made. An animated sequel series, The Legend of Korra, aired from 2012 to 2014. A new live-action remake of the series by its original creators to be produced for Netflix was announced in September 2018.",
  "2018-09-11", "2018-09-11"),
(1, "Even though the final season was disappointing, overall Game of Thrones was an great show",
  "Game of Thrones is an American fantasy drama television series created by David Benioff and D. B. Weiss for HBO. It is an adaptation of A Song of Ice and Fire, George R. R. Martin's series of fantasy novels, the first of which is A Game of Thrones. The show was both produced and filmed in Belfast and elsewhere in the United Kingdom. Filming locations also included Canada, Croatia, Iceland, Malta, Morocco, and Spain. The series premiered on HBO in the United States on April 17, 2011, and concluded on May 19, 2019, with 73 episodes broadcast over eight seasons.\r\rSet on the fictional continents of Westeros and Essos, Game of Thrones has several plots and a large ensemble cast and follows several story arcs. One arc is about the Iron Throne of the Seven Kingdoms and follows a web of alliances and conflicts among the noble dynasties either vying to claim the throne or fighting for independence from it. Another focuses on the last descendant of the realm's deposed ruling dynasty, who has been exiled and is plotting a return to the throne, while another story arc follows the Night's Watch, a brotherhood defending the realm against the fierce peoples and legendary creatures of the North.\r\rGame of Thrones attracted a record viewership on HBO and has a broad, active, and international fan base. It was acclaimed by critics for its acting, complex characters, story, scope, and production values, although its frequent use of nudity and violence (including sexual violence) was criticized. The series received 47 Primetime Emmy Awards, the most by a drama series, including Outstanding Drama Series in 2015, 2016, and 2018. Its other awards and nominations include three Hugo Awards for Best Dramatic Presentation (2012–2014), a 2011 Peabody Award, and five nominations for the Golden Globe Award for Best Television Series – Drama (2012 and 2015–2018). In 2019, the show's final season established a new record for most Emmy nominations received in the same year by any show with 32, breaking the 25 years long record of 26 nominations established by NYPD Blue in 1994; it also established Game of Thrones as the drama series with the most overall Emmy nominations, with a total of 161.",
  "2018-09-14", "2018-09-14"),
(2, "The Mission Impossible movies is one of the few film franchise that did not get worse overtime",
  "Mission: Impossible is a series of American action spy films both based on and a follow-on from the television series of the same name created by Bruce Geller. The series is co-produced by and stars Tom Cruise, whose character is Ethan Hunt, an agent of the Impossible Missions Force (IMF). Τhe original music for the movies has been written by Danny Elfman, Hans Zimmer, Michael Giacchino, Joe Kraemer, and Lorne Balfe.\r\rBeginning in 1996, the films (taking place starting six years after the events of the previous TV sequel series) follow the missions of the IMF's main field team under the leadership of Hunt, who is forced to take over after the team is betrayed from within during the first film. The series focuses on Hunt as the lead character as opposed to the ensemble cast structure of the television series, although some characters, such as Luther Stickell (played by Ving Rhames) and Benji Dunn (played by Simon Pegg) have recurring roles in the films.\r\rThe series has received a positive reception from critics and is the 16th-highest-grossing film series of all time, with a worldwide gross of over $3.5 billion to date. The sixth and most recent film, titled Mission: Impossible – Fallout, was released in July 2018, and was written and directed by Christopher McQuarrie.\r\rAll of the Mission: Impossible movies are released by Paramount Pictures and rated PG-13 by the Motion Picture Association of America.",
  "2018-10-11", "2018-10-11"),
(1, "Some stuff about the MCU - The Marvel Cinematic Universe",
  "The Marvel Cinematic Universe (MCU) is an American media franchise and shared universe centered on a series of superhero films, independently produced by Marvel Studios and based on characters that appear in American comic books published by Marvel Comics. The franchise also includes comic books, short films, television series, and digital series. The shared universe, much like the original Marvel Universe in comic books, was established by crossing over common plot elements, settings, cast, and characters.\r\rThe first MCU film was Iron Man (2008), which began the first phase of films culminating in the crossover film The Avengers (2012). Phase Two began with Iron Man 3 (2013) and concluded with Ant-Man (2015). Phase Three began with Captain America: Civil War (2016) and concluded with Spider-Man: Far From Home (2019). The first three phases in the franchise are collectively known as 'The Infinity Saga'. Phase Four will begin with Black Widow (2020) and is set to conclude with Thor: Love and Thunder (2021).\r\rMarvel Television expanded the universe to network television with Marvel's Agents of S.H.I.E.L.D. on ABC in the 2013–14 television season, followed by online streaming with Marvel's Daredevil on Netflix in 2015 and Marvel's Runaways on Hulu in 2017, and then to cable television with Marvel's Cloak & Dagger on Freeform in 2018. Marvel Television also produced the digital series Marvel's Agents of S.H.I.E.L.D.: Slingshot. Marvel Studios also expanded to online streaming with Disney+ for tie-in shows, starting with The Falcon and the Winter Soldier in 2020. Soundtrack albums have been released for all the films and many of the television series, as well compilation albums containing existing music heard in the films. The MCU also includes tie-in comics published by Marvel Comics, while Marvel Studios has also produced a series of direct-to-video short films and a viral marketing campaign for its films and the universe with the faux news program WHIH Newsfront.\r\rThe franchise has been commercially successful and has generally received a positive critical response, though some reviewers have found that some of its films and television series have suffered in service of the wider universe. It has inspired other film and television studios with comic book character adaptation rights to attempt to create similar shared universes. The MCU has also been the focus of other media, outside of the shared universe, including attractions at various Walt Disney Parks and Resorts, an attraction at Discovery Times Square, a Queensland Gallery of Modern Art exhibit, two television specials, guidebooks for each film, multiple tie-in video games, and commercials.",
  "2018-11-21", "2018-11-21");
